/* SPDX-License-Identifier: GPL-3.0-only */
#ifndef OPENRFS_ABI_BASE_H
#define OPENRFS_ABI_BASE_H

#include <stdint.h>

#define OPENRFS_ABI_VERSION UINT32_C(1)
#define OPENRFS_ABI_PAGE_SIZE UINT32_C(4096)

typedef uint64_t openrfs_handle_t;

#define OPENRFS_HANDLE_INVALID UINT64_C(0)

/* Signed syscall results use zero or a non-negative value on success. */
enum openrfs_errno {
    OPENRFS_EPERM = 1,
    OPENRFS_ENOENT = 2,
    OPENRFS_EIO = 5,
    OPENRFS_EBADF = 9,
    OPENRFS_EAGAIN = 11,
    OPENRFS_ENOMEM = 12,
    OPENRFS_EACCES = 13,
    OPENRFS_EFAULT = 14,
    OPENRFS_EBUSY = 16,
    OPENRFS_EEXIST = 17,
    OPENRFS_ENOTDIR = 20,
    OPENRFS_EISDIR = 21,
    OPENRFS_EINVAL = 22,
    OPENRFS_EMFILE = 24,
    OPENRFS_ENOSPC = 28,
    OPENRFS_EROFS = 30,
    OPENRFS_EPIPE = 32,
    OPENRFS_ENAMETOOLONG = 36,
    OPENRFS_ENOSYS = 38,
    OPENRFS_ENOTEMPTY = 39,
    OPENRFS_ELOOP = 40,
    OPENRFS_ENOTSUP = 95,
    OPENRFS_ETIMEDOUT = 110,
    OPENRFS_ECANCELED = 125,
    OPENRFS_ESTALE = 127
};

/* RAX is the number; RDI, RSI, RDX, R10, R8 and R9 carry arguments. */
enum openrfs_syscall_number {
    OPENRFS_SYS_ABI_VERSION = 0x0000,
    OPENRFS_SYS_EXIT = 0x0001,
    OPENRFS_SYS_CONSOLE_WRITE = 0x0002,
    OPENRFS_SYS_CONSOLE_READ = 0x0003,
    OPENRFS_SYS_HANDLE_CLOSE = 0x0004,
    OPENRFS_SYS_HANDLE_DUPLICATE = 0x0005,

    OPENRFS_SYS_MEMORY_MAP = 0x0100,
    OPENRFS_SYS_MEMORY_UNMAP = 0x0101,

    OPENRFS_SYS_FILE_OPEN = 0x0200,
    OPENRFS_SYS_FILE_READ = 0x0201,
    OPENRFS_SYS_FILE_WRITE = 0x0202,
    OPENRFS_SYS_FILE_SEEK = 0x0203,
    OPENRFS_SYS_PATH_STAT = 0x0204,
    OPENRFS_SYS_DIRECTORY_OPEN = 0x0205,
    OPENRFS_SYS_DIRECTORY_READ = 0x0206,
    OPENRFS_SYS_PATH_MKDIR = 0x0207,
    OPENRFS_SYS_PATH_RENAME = 0x0208,
    OPENRFS_SYS_PATH_REPLACE = 0x0209,
    OPENRFS_SYS_PATH_UNLINK = 0x020A,
    OPENRFS_SYS_PATH_TRUNCATE = 0x020B,
    OPENRFS_SYS_VOLUME_SYNC = 0x020C,
    OPENRFS_SYS_VOLUME_SPACE = 0x020D,
    OPENRFS_SYS_PATH_SYMLINK = 0x020E,
    OPENRFS_SYS_PATH_READLINK = 0x020F,
    OPENRFS_SYS_PATH_CHMOD = 0x0210,
    OPENRFS_SYS_PATH_XATTR = 0x0211,
    OPENRFS_SYS_DIRECTORY_READ_LONG = 0x0212,
    OPENRFS_SYS_FILE_TRUNCATE = 0x0213,
    OPENRFS_SYS_PATH_SET_TIMES = 0x0214,
    OPENRFS_SYS_PATH_LINK = 0x0215,
    OPENRFS_SYS_PATH_METADATA = 0x0216,
    OPENRFS_SYS_FILE_SYNC = 0x0217,
    OPENRFS_SYS_FILE_METADATA = 0x0218,
    OPENRFS_SYS_FILE_PUBLISH = 0x0219,
    OPENRFS_SYS_FILE_UNLINK = 0x021A,

    OPENRFS_SYS_TIME_MONOTONIC = 0x0300,
    OPENRFS_SYS_SLEEP_UNTIL = 0x0301,
    OPENRFS_SYS_WAIT = 0x0302,
    OPENRFS_SYS_RANDOM = 0x0303,
    OPENRFS_SYS_TIMER_CREATE = 0x0304,
    OPENRFS_SYS_TIMER_SET = 0x0305,
    OPENRFS_SYS_CANCEL = 0x0306,
    OPENRFS_SYS_TIME_REALTIME = 0x0307,
    OPENRFS_SYS_RANDOM_STRONG = 0x0308,

    OPENRFS_SYS_WINDOW_CREATE = 0x0400,
    OPENRFS_SYS_SURFACE_PRESENT = 0x0401,
    OPENRFS_SYS_EVENT_READ = 0x0402,
    OPENRFS_SYS_POINTER_CAPTURE = 0x0403,

    OPENRFS_SYS_DNS_RESOLVE = 0x0500,
    OPENRFS_SYS_STREAM_OPEN = 0x0501,
    OPENRFS_SYS_STREAM_CONNECT = 0x0502,
    OPENRFS_SYS_STREAM_READ = 0x0503,
    OPENRFS_SYS_STREAM_WRITE = 0x0504,
    OPENRFS_SYS_STREAM_SHUTDOWN = 0x0505,
    OPENRFS_SYS_DATAGRAM_OPEN = 0x0506,
    OPENRFS_SYS_DATAGRAM_BIND = 0x0507,
    OPENRFS_SYS_DATAGRAM_SEND = 0x0508,
    OPENRFS_SYS_DATAGRAM_RECEIVE = 0x0509,
    OPENRFS_SYS_NETWORK_ADDRESS = 0x050A,

    OPENRFS_SYS_THREAD_CREATE = 0x0600,
    OPENRFS_SYS_THREAD_EXIT = 0x0601,
    OPENRFS_SYS_THREAD_JOIN = 0x0602,
    OPENRFS_SYS_TLS_SET = 0x0603,
    OPENRFS_SYS_TLS_GET = 0x0604,
    OPENRFS_SYS_FUTEX_WAIT = 0x0605,
    OPENRFS_SYS_FUTEX_WAKE = 0x0606,

    OPENRFS_SYS_AUDIO_OPEN = 0x0700,
    OPENRFS_SYS_AUDIO_SUBMIT = 0x0701,
    OPENRFS_SYS_AUDIO_VOLUME = 0x0702,
    OPENRFS_SYS_AUDIO_DRAIN = 0x0703,

    OPENRFS_SYS_PACKAGE_UPLOAD_OPEN = 0x0800,
    OPENRFS_SYS_PACKAGE_UPLOAD_WRITE = 0x0801,
    OPENRFS_SYS_PACKAGE_UPLOAD_SEAL = 0x0802,
    OPENRFS_SYS_PACKAGE_CONTROL_OPEN_INSTALL = 0x0803,
    OPENRFS_SYS_PACKAGE_CONTROL_ITEM = 0x0804,
    OPENRFS_SYS_PACKAGE_CONTROL_ATTACH = 0x0805,
    OPENRFS_SYS_PACKAGE_CONTROL_COMMIT = 0x0806
};

enum openrfs_capability {
    OPENRFS_CAP_CONSOLE = UINT64_C(1) << 0,
    OPENRFS_CAP_SYSTEM_READ = UINT64_C(1) << 1,
    OPENRFS_CAP_DATA_READ = UINT64_C(1) << 2,
    OPENRFS_CAP_DATA_WRITE = UINT64_C(1) << 3,
    OPENRFS_CAP_TIME = UINT64_C(1) << 4,
    OPENRFS_CAP_ENTROPY = UINT64_C(1) << 5,
    OPENRFS_CAP_WINDOW = UINT64_C(1) << 6,
    OPENRFS_CAP_INPUT = UINT64_C(1) << 7,
    OPENRFS_CAP_NETWORK = UINT64_C(1) << 8,
    OPENRFS_CAP_THREADS = UINT64_C(1) << 9,
    OPENRFS_CAP_AUDIO = UINT64_C(1) << 10,
    OPENRFS_CAP_PACKAGES = UINT64_C(1) << 11
};

#define OPENRFS_CAP_ALL_V1 ((UINT64_C(1) << 12) - UINT64_C(1))

enum openrfs_handle_type {
    OPENRFS_HANDLE_FILE = 1,
    OPENRFS_HANDLE_DIRECTORY = 2,
    OPENRFS_HANDLE_WINDOW = 3,
    OPENRFS_HANDLE_EVENT_QUEUE = 4,
    OPENRFS_HANDLE_STREAM = 5,
    OPENRFS_HANDLE_DATAGRAM = 6,
    OPENRFS_HANDLE_TIMER = 7,
    OPENRFS_HANDLE_THREAD = 8,
    OPENRFS_HANDLE_AUDIO_OUTPUT = 9,
    OPENRFS_HANDLE_PACKAGE_UPLOAD = 10,
    OPENRFS_HANDLE_PACKAGE_CONTROL = 11
};

#endif
