#!/usr/bin/env python3
"""Turn a coddy.tech capture into src/rsd_mark.h.

    python3 tools/make-mark.py assets/ascii/rsd-mark-45.json

The art is not written by hand and not copied out of a screenshot. It is
whatever tools/capture-ascii.py read back off the generator's own page,
and this turns that file into a header. Re-run the capture, re-run this,
and the art in the build is the art the generator produced today.

The generated header records the capture's settings and the sha256 of
the drawing that went in, the same way make-font.py records the TTF's.
"""
import hashlib
import json
import os
import sys

GRADIENT = " .:-=+*%#"


def main():
    if len(sys.argv) != 2:
        raise SystemExit("usage: make-mark.py <capture.json>")
    path = sys.argv[1]
    cap = json.load(open(path))
    rows = [r["text"].rstrip() for r in cap["rows"]]

    # The generator pads the block with empty lines top and bottom. They
    # are the image's margin, not the drawing, and a header that carried
    # them would make every caller guess how many to skip.
    while rows and not rows[0].strip():
        rows.pop(0)
    while rows and not rows[-1].strip():
        rows.pop()
    if not rows:
        raise SystemExit("%s has no art in it" % path)

    stray = sorted({c for r in rows for c in r} - set(GRADIENT))
    if stray:
        raise SystemExit("characters outside the gradient: %r" % stray)

    # The drawing the capture was taken from, which lives beside the
    # logo rather than beside the capture.
    source = os.path.join(os.path.dirname(path), "..", "logo",
                          "rsd-mark.png")
    digest = hashlib.sha256(open(source, "rb").read()).hexdigest()
    width = int(cap["settings"]["width"])

    out = open("src/rsd_mark.h", "w")
    out.write('/* SPDX-License-Identifier: GPL-3.0-only */\n')
    out.write("/* Generated by tools/make-mark.py. Do not edit.\n"
              " *\n"
              " * The mark as characters, straight off coddy.tech's ASCII\n"
              " * art generator:\n"
              " *\n"
              " *   https://coddy.tech/tools/ascii-art-generator\n"
              " *   Mode Image, Style Shaded, Color %s, Invert %s, Width %d\n"
              " *\n"
              " * Input assets/logo/rsd-mark.png, sha256\n"
              " *   %s\n"
              " *\n"
              " * The capture it came from is assets/ascii/rsd-mark-45.json,\n"
              " * taken by tools/capture-ascii.py driving the page. Nothing here\n"
              " * was drawn, traced or adjusted by hand.\n"
              " */\n"
              % ("on" if cap["settings"]["colour"] else "off",
                 "on" if cap["settings"]["invert"] else "off",
                 width, digest))
    out.write("#ifndef RSD_MARK_H\n#define RSD_MARK_H\n\n#include <stdint.h>\n\n")
    out.write("#define RSD_MARK_COLS %dU\n\n" % width)
    out.write("static const char *const RSD_MARK[] = {\n")
    for r in rows:
        out.write('    "%s",\n' % r.replace("\\", "\\\\").replace('"', '\\"'))
    out.write("};\n\n")
    out.write("#define RSD_MARK_ROWS "
              "(sizeof(RSD_MARK) / sizeof(RSD_MARK[0]))\n\n")
    out.write('''/*
 * The generator's ramp, darkest first. Brightness is read off this
 * rather than by testing characters, so nothing can disagree with the
 * generator the day the ramp changes.
 *
 * The capture carries a colour per character too. It is not used: every
 * one of the 171 distinct colours in it is a red between 195 and 231,
 * which is one colour as far as a sixteen-colour console is concerned.
 * The gradient is where the drawing's detail actually lives.
 */
#define RSD_MARK_GRADIENT "%s"

/* Nine steps of gradient folded into four of ink: nothing, a trace, ink
 * and the densest. Four because the console has two reds and a shade
 * glyph, and a fifth level would have nowhere to go. */
static inline uint32_t rsd_mark_ink(char c)
{
    const char *ramp = RSD_MARK_GRADIENT;
    uint32_t i;

    for (i = 0U; ramp[i] != '\\0'; ++i) {
        if (ramp[i] == c) {
            return (i + 2U) / 3U;
        }
    }
    return 0U;
}

#endif /* RSD_MARK_H */
''' % GRADIENT)
    out.close()
    print("wrote src/rsd_mark.h: %d rows, width %d, %d inked cells"
          % (len(rows), width,
             sum(1 for r in rows for c in r if c != " ")))


main()
