/* SPDX-License-Identifier: GPL-3.0-only */
#ifndef OPENGAT_ABI_BASE_H
#define OPENGAT_ABI_BASE_H

#include <stdint.h>

#define OPENGAT_ABI_VERSION UINT32_C(1)
#define OPENGAT_ABI_PAGE_SIZE UINT32_C(4096)

typedef uint64_t opengat_handle_t;

#define OPENGAT_HANDLE_INVALID UINT64_C(0)

/* Signed syscall results use zero or a non-negative value on success. */
enum opengat_errno {
    OPENGAT_EPERM = 1,
    OPENGAT_ENOENT = 2,
    OPENGAT_EIO = 5,
    OPENGAT_EBADF = 9,
    OPENGAT_EAGAIN = 11,
    OPENGAT_ENOMEM = 12,
    OPENGAT_EACCES = 13,
    OPENGAT_EFAULT = 14,
    OPENGAT_EBUSY = 16,
    OPENGAT_EEXIST = 17,
    OPENGAT_ENOTDIR = 20,
    OPENGAT_EISDIR = 21,
    OPENGAT_EINVAL = 22,
    OPENGAT_ENOSPC = 28,
    OPENGAT_EROFS = 30,
    OPENGAT_EPIPE = 32,
    OPENGAT_ENAMETOOLONG = 36,
    OPENGAT_ENOSYS = 38,
    OPENGAT_ENOTEMPTY = 39,
    OPENGAT_ELOOP = 40,
    OPENGAT_ENOTSUP = 95,
    OPENGAT_ETIMEDOUT = 110,
    OPENGAT_ECANCELED = 125,
    OPENGAT_ESTALE = 127
};

/* RAX is the number; RDI, RSI, RDX, R10, R8 and R9 carry arguments. */
enum opengat_syscall_number {
    OPENGAT_SYS_ABI_VERSION = 0x0000,
    OPENGAT_SYS_EXIT = 0x0001,
    OPENGAT_SYS_CONSOLE_WRITE = 0x0002,
    OPENGAT_SYS_CONSOLE_READ = 0x0003,
    OPENGAT_SYS_HANDLE_CLOSE = 0x0004,
    OPENGAT_SYS_HANDLE_DUPLICATE = 0x0005,

    OPENGAT_SYS_MEMORY_MAP = 0x0100,
    OPENGAT_SYS_MEMORY_UNMAP = 0x0101,

    OPENGAT_SYS_FILE_OPEN = 0x0200,
    OPENGAT_SYS_FILE_READ = 0x0201,
    OPENGAT_SYS_FILE_WRITE = 0x0202,
    OPENGAT_SYS_FILE_SEEK = 0x0203,
    OPENGAT_SYS_PATH_STAT = 0x0204,
    OPENGAT_SYS_DIRECTORY_OPEN = 0x0205,
    OPENGAT_SYS_DIRECTORY_READ = 0x0206,
    OPENGAT_SYS_PATH_MKDIR = 0x0207,
    OPENGAT_SYS_PATH_RENAME = 0x0208,
    OPENGAT_SYS_PATH_REPLACE = 0x0209,
    OPENGAT_SYS_PATH_UNLINK = 0x020A,
    OPENGAT_SYS_PATH_TRUNCATE = 0x020B,
    OPENGAT_SYS_VOLUME_SYNC = 0x020C,
    OPENGAT_SYS_VOLUME_SPACE = 0x020D,

    OPENGAT_SYS_TIME_MONOTONIC = 0x0300,
    OPENGAT_SYS_SLEEP_UNTIL = 0x0301,
    OPENGAT_SYS_WAIT = 0x0302,
    OPENGAT_SYS_RANDOM = 0x0303,
    OPENGAT_SYS_TIMER_CREATE = 0x0304,
    OPENGAT_SYS_TIMER_SET = 0x0305,
    OPENGAT_SYS_CANCEL = 0x0306,
    OPENGAT_SYS_TIME_REALTIME = 0x0307,
    OPENGAT_SYS_RANDOM_STRONG = 0x0308,

    OPENGAT_SYS_WINDOW_CREATE = 0x0400,
    OPENGAT_SYS_SURFACE_PRESENT = 0x0401,
    OPENGAT_SYS_EVENT_READ = 0x0402,
    OPENGAT_SYS_POINTER_CAPTURE = 0x0403,

    OPENGAT_SYS_DNS_RESOLVE = 0x0500,
    OPENGAT_SYS_STREAM_OPEN = 0x0501,
    OPENGAT_SYS_STREAM_CONNECT = 0x0502,
    OPENGAT_SYS_STREAM_READ = 0x0503,
    OPENGAT_SYS_STREAM_WRITE = 0x0504,
    OPENGAT_SYS_STREAM_SHUTDOWN = 0x0505,
    OPENGAT_SYS_DATAGRAM_OPEN = 0x0506,
    OPENGAT_SYS_DATAGRAM_BIND = 0x0507,
    OPENGAT_SYS_DATAGRAM_SEND = 0x0508,
    OPENGAT_SYS_DATAGRAM_RECEIVE = 0x0509,
    OPENGAT_SYS_NETWORK_ADDRESS = 0x050A,

    OPENGAT_SYS_THREAD_CREATE = 0x0600,
    OPENGAT_SYS_THREAD_EXIT = 0x0601,
    OPENGAT_SYS_THREAD_JOIN = 0x0602,
    OPENGAT_SYS_TLS_SET = 0x0603,
    OPENGAT_SYS_TLS_GET = 0x0604,
    OPENGAT_SYS_FUTEX_WAIT = 0x0605,
    OPENGAT_SYS_FUTEX_WAKE = 0x0606,

    OPENGAT_SYS_AUDIO_OPEN = 0x0700,
    OPENGAT_SYS_AUDIO_SUBMIT = 0x0701,
    OPENGAT_SYS_AUDIO_VOLUME = 0x0702,
    OPENGAT_SYS_AUDIO_DRAIN = 0x0703,

    OPENGAT_SYS_PACKAGE_UPLOAD_OPEN = 0x0800,
    OPENGAT_SYS_PACKAGE_UPLOAD_WRITE = 0x0801,
    OPENGAT_SYS_PACKAGE_UPLOAD_SEAL = 0x0802,
    OPENGAT_SYS_PACKAGE_CONTROL_OPEN_INSTALL = 0x0803,
    OPENGAT_SYS_PACKAGE_CONTROL_ITEM = 0x0804,
    OPENGAT_SYS_PACKAGE_CONTROL_ATTACH = 0x0805,
    OPENGAT_SYS_PACKAGE_CONTROL_COMMIT = 0x0806
};

enum opengat_capability {
    OPENGAT_CAP_CONSOLE = UINT64_C(1) << 0,
    OPENGAT_CAP_SYSTEM_READ = UINT64_C(1) << 1,
    OPENGAT_CAP_DATA_READ = UINT64_C(1) << 2,
    OPENGAT_CAP_DATA_WRITE = UINT64_C(1) << 3,
    OPENGAT_CAP_TIME = UINT64_C(1) << 4,
    OPENGAT_CAP_ENTROPY = UINT64_C(1) << 5,
    OPENGAT_CAP_WINDOW = UINT64_C(1) << 6,
    OPENGAT_CAP_INPUT = UINT64_C(1) << 7,
    OPENGAT_CAP_NETWORK = UINT64_C(1) << 8,
    OPENGAT_CAP_THREADS = UINT64_C(1) << 9,
    OPENGAT_CAP_AUDIO = UINT64_C(1) << 10,
    OPENGAT_CAP_PACKAGES = UINT64_C(1) << 11
};

#define OPENGAT_CAP_ALL_V1 ((UINT64_C(1) << 12) - UINT64_C(1))

enum opengat_handle_type {
    OPENGAT_HANDLE_FILE = 1,
    OPENGAT_HANDLE_DIRECTORY = 2,
    OPENGAT_HANDLE_WINDOW = 3,
    OPENGAT_HANDLE_EVENT_QUEUE = 4,
    OPENGAT_HANDLE_STREAM = 5,
    OPENGAT_HANDLE_DATAGRAM = 6,
    OPENGAT_HANDLE_TIMER = 7,
    OPENGAT_HANDLE_THREAD = 8,
    OPENGAT_HANDLE_AUDIO_OUTPUT = 9,
    OPENGAT_HANDLE_PACKAGE_UPLOAD = 10,
    OPENGAT_HANDLE_PACKAGE_CONTROL = 11
};

#endif
