/* SPDX-License-Identifier: GPL-3.0-only */
/* Generated by tools/make-mark.py. Do not edit.
 *
 * The mark as characters, straight off coddy.tech's ASCII
 * art generator:
 *
 *   https://coddy.tech/tools/ascii-art-generator
 *   Mode Image, Style Shaded, Color on, Invert off, Width 45
 *
 * Input assets/logo/rsd-mark.png, sha256
 *   79973fb0f2814bfb9d148e390acc8b3027403b2296cee9af591694f28cda8788
 *
 * The capture it came from is assets/ascii/rsd-mark-45.json,
 * taken by tools/capture-ascii.py driving the page. Nothing here
 * was drawn, traced or adjusted by hand.
 */
#ifndef RSD_MARK_H
#define RSD_MARK_H

#include <stdint.h>

#define RSD_MARK_COLS 45U

static const char *const RSD_MARK[] = {
    " %%%%%%%%%%      %%%%%%%%%     %%%%%%%%%",
    "%%%      %%%%  %%%%     %%%  %%%      %%%%%",
    "%%         %%% %%%           %%%         %%%",
    "%%        %%%  %%%%          %%%          %%%",
    "%%%     %%%%     %%%%%       %%%           %%",
    "%%%%%%%%%%          %%%%%%   %%%           %%",
    "%%    %%%%              %%%% %%%          %%%",
    "%%      %%%%             %%%%%%%         %%%",
    "%%       %%%%   %%%     %%%% %%%      %%%%%",
    "%%         %%%  %%%%%%%%%%   %%%%%%%%%%%",
};

#define RSD_MARK_ROWS (sizeof(RSD_MARK) / sizeof(RSD_MARK[0]))

/*
 * The generator's ramp, darkest first. Brightness is read off this
 * rather than by testing characters, so nothing can disagree with the
 * generator the day the ramp changes.
 *
 * The capture carries a colour per character too. It is not used: every
 * one of the 171 distinct colours in it is a red between 195 and 231,
 * which is one colour as far as a sixteen-colour console is concerned.
 * The gradient is where the drawing's detail actually lives.
 */
#define RSD_MARK_GRADIENT " .:-=+*%#"

/* Nine steps of gradient folded into four of ink: nothing, a trace, ink
 * and the densest. Four because the console has two reds and a shade
 * glyph, and a fifth level would have nowhere to go. */
static inline uint32_t rsd_mark_ink(char c)
{
    const char *ramp = RSD_MARK_GRADIENT;
    uint32_t i;

    for (i = 0U; ramp[i] != '\0'; ++i) {
        if (ramp[i] == c) {
            return (i + 2U) / 3U;
        }
    }
    return 0U;
}

#endif /* RSD_MARK_H */
