/* SPDX-License-Identifier: GPL-3.0-only */
/*
 * GENERATED by tools/make-glass.py - do not edit.
 *
 * Oxygen's derived colours for this desktop's bases,
 * put through KColorScheme::shade() in HCY rather than
 * scaled per channel. Scaling clips: a light grey times
 * 1.12 is white, and a window whose top is white has no
 * gradient left to run down it.
 *
 * tools/make-glass.py quotes every formula and names
 * the file it came out of.
 */
#ifndef RSD_GLASS_H
#define RSD_GLASS_H

#include <stdint.h>

/*
 * THE SPLIT, from oxygenhelper.cpp
 * renderWindowBackground():
 *
 *     const int splitY(qMin(300.0, (3 * windowRect.height()) / 4));
 *
 * Above it the window runs top -> base -> bottom;
 * below it it is flat. A tall window settles instead of
 * getting darker forever.
 */
#define RSD_GLASS_SPLIT 300U

/*
 * THE POOL OF LIGHT AT THE TOP, which is the other half
 * of renderWindowBackground() and the half that gets
 * left out: a radial highlight 64 pixels tall, at most
 * 600 wide, centred on the top edge. Its stops are
 * alpha 255, 101, 37, 0 at 0, 0.5, 0.75 and 1 of the
 * radius, out of Helper::radialGradient().
 */
#define RSD_GLASS_POOL_WIDE 600U
#define RSD_GLASS_POOL_HIGH 64U

/*
 * The pool's alpha, indexed by the SQUARED distance
 * from its centre - 0 at the middle of the top edge, 255
 * where the light has run out:
 *
 *     q = dx * dx * 256 / (WIDE / 2)^2
 *       + dy * dy * 256 / HIGH^2
 *
 * Squared, so the shell needs no square root; the stops
 * are interpolated here against the root of it, which is
 * what Qt does along the radius.
 */
static const uint8_t rsd_glass_pool[256] = {
     255, 236, 228, 222, 216, 212, 208, 204, 200, 197, 194, 191, 188, 185, 183, 180,
     178, 175, 173, 171, 169, 167, 165, 162, 161, 159, 157, 155, 153, 151, 149, 148,
     146, 144, 143, 141, 139, 138, 136, 135, 133, 131, 130, 129, 127, 126, 124, 123,
     121, 120, 119, 117, 116, 115, 113, 112, 111, 109, 108, 107, 106, 104, 103, 102,
     101, 100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,  87,  87,
      86,  85,  84,  83,  82,  81,  80,  79,  79,  78,  77,  76,  75,  74,  74,  73,
      72,  71,  70,  69,  69,  68,  67,  66,  66,  65,  64,  63,  62,  62,  61,  60,
      59,  59,  58,  57,  56,  56,  55,  54,  53,  53,  52,  51,  50,  50,  49,  48,
      48,  47,  46,  46,  45,  44,  43,  43,  42,  41,  41,  40,  39,  39,  38,  37,
      37,  36,  36,  36,  35,  35,  34,  34,  34,  33,  33,  33,  32,  32,  32,  31,
      31,  30,  30,  30,  29,  29,  29,  28,  28,  28,  27,  27,  26,  26,  26,  25,
      25,  25,  24,  24,  24,  23,  23,  23,  22,  22,  22,  21,  21,  21,  20,  20,
      20,  19,  19,  19,  18,  18,  18,  17,  17,  17,  16,  16,  16,  15,  15,  15,
      14,  14,  14,  13,  13,  13,  12,  12,  12,  11,  11,  11,  11,  10,  10,  10,
       9,   9,   9,   8,   8,   8,   7,   7,   7,   7,   6,   6,   6,   5,   5,   5,
       4,   4,   4,   4,   3,   3,   3,   2,   2,   2,   1,   1,   1,   1,   0,   0,
};

/* the window, and the focused frame: 0xD6D2D0 */
#define RSD_GLASS_ACTIVE 0xD6D2D0U
#define RSD_GLASS_ACTIVE_TOP 0xE2DFDEU
#define RSD_GLASS_ACTIVE_BOTTOM 0xC1BBB8U
#define RSD_GLASS_ACTIVE_RADIAL 0xFFFFFFU
#define RSD_GLASS_ACTIVE_LIGHT 0xFCFCFCU
#define RSD_GLASS_ACTIVE_DARK 0xB3ABA7U
#define RSD_GLASS_ACTIVE_SHADOW 0x3E3B3AU

/* an unfocused window's frame: 0xE0DFDE */
#define RSD_GLASS_IDLE 0xE0DFDEU
#define RSD_GLASS_IDLE_TOP 0xEDEDECU
#define RSD_GLASS_IDLE_BOTTOM 0xC8C6C4U
#define RSD_GLASS_IDLE_RADIAL 0xFFFFFFU
#define RSD_GLASS_IDLE_LIGHT 0xFFFFFFU
#define RSD_GLASS_IDLE_DARK 0xB7B5B3U
#define RSD_GLASS_IDLE_SHADOW 0x3D3C3CU

#endif /* RSD_GLASS_H */
