/* SPDX-License-Identifier: GPL-3.0-only */
/*
 * GENERATED by tools/make-logo.py - do not edit.
 *
 * The characters AND their colours are rsd-mark-45.json,
 * which is coddy.tech's ASCII art generator run over the
 * drawing with Color on and the width at 45.  Nothing here is
 * classified or averaged: every cell is the cell that
 * generator produced, with its colour snapped to the nearest
 * of 3.  assets/logo/SOURCE.txt records the settings and
 * whose drawing it is.
 */
#ifndef RSD_LOGO_H
#define RSD_LOGO_H

#define RSD_LOGO_ROWS 10U
#define RSD_LOGO_COLUMNS 45U
#define RSD_LOGO_INKS 4U

/*
 * THE MARK'S OWN COLOURS, reduced from the 36 the capture
 * holds to 3 by k-means over the cells that use them.
 * Entry 0 is not a colour: a cell with nothing drawn in it
 * takes the terminal's own foreground.
 */
static const uint32_t rsd_logo_ink[RSD_LOGO_INKS] = {
    0x000000U,   /* unused: index 0 means the terminal's ink */
    0x650000U,
    0x700100U,
    0x780100U,
};

static const char *const rsd_logo[RSD_LOGO_ROWS] = {
    " %%%%%%%%%%      %%%%%%%%%     %%%%%%%%%",
    "%%%      %%%%  %%%%     %%%  %%%      %%%%%",
    "%%         %%% %%%           %%%         %%%",
    "%%        %%%  %%%%          %%%          %%%",
    "%%%     %%%%     %%%%%       %%%           %%",
    "%%%%%%%%%%          %%%%%%   %%%           %%",
    "%%    %%%%              %%%% %%%          %%%",
    "%%      %%%%             %%%%%%%         %%%",
    "%%       %%%%   %%%     %%%% %%%      %%%%%",
    "%%         %%%  %%%%%%%%%%   %%%%%%%%%%%",
};

/* One hex digit per character of the row above: an index into
 * rsd_logo_ink, and 0 where nothing is drawn. */
static const char *const rsd_logo_at[RSD_LOGO_ROWS] = {
    "0333333333300000033333333300000333333332",
    "3330000003333003332000002320033300000023332",
    "33000000000331033300000000000233000000000333",
    "330000000033300333200000000002330000000000233",
    "332000002333000003333300000002330000000000033",
    "333333333200000000002333320002330000000000033",
    "330000333300000000000000233302330000000000333",
    "33000000333300000000000003331233000000000333",
    "3300000002333000333000003333023300000023333",
    "3300000000033300333333333300033333333333",
};

#endif /* RSD_LOGO_H */
