#!/usr/bin/env python3
"""Generate the bounded OpenRFS panel mark from the canonical RGBA logo."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path


def load_logo_tools():
    path = Path(__file__).with_name("make-logo-asset.py")
    spec = importlib.util.spec_from_file_location("make_logo_asset", path)
    if spec is None or spec.loader is None:
        raise SystemExit("could not load make-logo-asset.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def square_plane(tools, pixels: bytes, width: int, height: int, size: int) -> bytes:
    if width >= height:
        out_width = size
        out_height = max(1, (height * size + width // 2) // width)
    else:
        out_height = size
        out_width = max(1, (width * size + height // 2) // height)
    scaled = tools.downscale(pixels, width, height, out_width, out_height)
    plane = bytearray(size * size * 4)
    left = (size - out_width) // 2
    top = (size - out_height) // 2
    for y in range(out_height):
        source = y * out_width * 4
        destination = ((top + y) * size + left) * 4
        plane[destination:destination + out_width * 4] = \
            scaled[source:source + out_width * 4]
    return bytes(plane)


def values(items: list[int], width: int) -> str:
    rows = []
    for offset in range(0, len(items), width):
        rows.append("    " + ", ".join(items[offset:offset + width]) + ",")
    return "\n".join(rows)


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: make-brand-mark.py INPUT.png OUTPUT.h")
    tools = load_logo_tools()
    width, height, pixels = tools.read_png(sys.argv[1])
    width, height, pixels = tools.crop_to_primary_mark(
        pixels, width, height, threshold=8, padding=0
    )
    sizes = (16, 20, 24)
    planes = {size: square_plane(tools, pixels, width, height, size)
              for size in sizes}
    output = [
        "/* SPDX-License-Identifier: GPL-3.0-only */",
        "/* GENERATED by tools/make-brand-mark.py; do not edit. */",
        "#ifndef OPENRFS_BRAND_MARK_H",
        "#define OPENRFS_BRAND_MARK_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "#define OPENRFS_MARK_SIZES 3U",
        "",
        "static const uint32_t openrfs_mark_size[OPENRFS_MARK_SIZES] = {",
        "    16U, 20U, 24U",
        "};",
        "",
    ]
    for size in sizes:
        plane = planes[size]
        colors = []
        alpha = []
        for offset in range(0, len(plane), 4):
            colors.append(
                f"0x00{plane[offset]:02X}{plane[offset + 1]:02X}{plane[offset + 2]:02X}U"
            )
            alpha.append(f"{plane[offset + 3]:3d}")
        output.extend([
            f"static const uint32_t openrfs_mark_openrfs_{size}_pixels[{size} * {size}] = {{",
            values(colors, 8),
            "};",
            f"static const uint8_t openrfs_mark_openrfs_{size}_alpha[{size} * {size}] = {{",
            values(alpha, 16),
            "};",
            "",
        ])
    output.extend([
        "struct openrfs_mark_entry {",
        "    const char *name;",
        "    const uint32_t *pixels[OPENRFS_MARK_SIZES];",
        "    const uint8_t *alpha[OPENRFS_MARK_SIZES];",
        "};",
        "",
        "static const struct openrfs_mark_entry openrfs_mark[] = {",
        "    { \"openrfs\",",
        "      { openrfs_mark_openrfs_16_pixels, openrfs_mark_openrfs_20_pixels, openrfs_mark_openrfs_24_pixels },",
        "      { openrfs_mark_openrfs_16_alpha, openrfs_mark_openrfs_20_alpha, openrfs_mark_openrfs_24_alpha } },",
        "};",
        "",
        "#define OPENRFS_MARK_COUNT (sizeof(openrfs_mark) / sizeof(openrfs_mark[0]))",
        "",
        "#endif",
        "",
    ])
    Path(sys.argv[2]).write_text("\n".join(output))
    print(f"{sys.argv[1]}: {width}x{height} -> {sizes} -> {sys.argv[2]}")


if __name__ == "__main__":
    main()
