#!/usr/bin/env python3
"""The desktop's text, rasterised ahead of time.

    python3 tools/make-font.py

WHY THIS REPLACED THE BITMAP FONT, which is the point of the whole pass.

The faces were Misc-Fixed 6x13, 7x14 and 9x18 - X11 bitmap fonts, one
bit per pixel, no shades, no curves.  They are the right faces for an
X session of 1995 and they are the single loudest thing on this screen
saying 1995.  You can put any amount of gradient and rounding round a
window and it will still read as twenty years older than it is while the
words on it are a bitmap font: type is the first thing anybody sees and
the last thing they stop seeing.

So the type is what changed first.  DejaVu Sans, antialiased, at the
size KDE 4 came up in - its default UI font was "Sans Serif 9", which
fontconfig resolved to DejaVu Sans on every distribution that shipped
KDE 4, and 9 points at 96 dpi is a 12-pixel em.  The terminal gets
DejaVu Sans Mono, which is what Konsole came up in.

Coverage, not bits.  Every byte here is 0..255 and the drawing code
tints it, so the shell gets antialiased text everywhere for free - the
one change that does most of the work of making this look like a desktop
of 2010 rather than a framebuffer demo.

WHAT IS AND IS NOT VENDORED.  Nothing here copies a font file into the
repository.  This reads the TrueType files off the build machine and
writes the coverage tables, and assets/fonts/SOURCE.txt records which
file each face came from, its sha256 and its licence.
"""
import hashlib
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "desktop" / "src"

SANS = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
MONO = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"

FIRST = 32
LAST = 126

# (header stem, macro prefix, file, em pixels, human name).
#
# Three sizes of the UI face because Settings offers a list of them and a
# size nobody rasterised would be a row that does nothing.  12 is the
# middle one and the one a session comes up in: 9 points at 96 dpi.
FACES = [
    ("rsd_font_sans_11", "RSD_FONT_SANS_11", SANS, 11,
     "DejaVu Sans 8"),
    ("rsd_font_sans_12", "RSD_FONT_SANS_12", SANS, 12,
     "DejaVu Sans 9"),
    ("rsd_font_sans_14", "RSD_FONT_SANS_14", SANS, 14,
     "DejaVu Sans 10.5"),
    ("rsd_mono", "RSD_MONO", MONO, 12,
     "DejaVu Sans Mono 9"),
]


def rasterise(path, em):
    """One face: (ascent, descent, [(code, advance, width, rows)])."""
    font = ImageFont.truetype(path, em)
    ascent, descent = font.getmetrics()
    height = ascent + descent
    glyphs = []

    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        advance = int(round(font.getlength(ch)))
        box = font.getbbox(ch)          # (x0, y0, x1, y1) from the
                                        # left edge and the ascender
        # The cell has to hold whichever is wider: the advance, or ink
        # that reaches past it.  Italic-style overhang does not arise in
        # this face, but a comma's tail and a 'W' at small sizes both do.
        width = max(advance, int(box[2]) + 1, 1)
        cell = Image.new("L", (width, height), 0)
        # Anchor "la" is left, ascender - so (0, 0) is the pen position
        # on the ascender line, which is exactly where the drawing code
        # starts its cell: baseline - ascent.
        ImageDraw.Draw(cell).text((0, 0), ch, font=font, fill=255,
                                  anchor="la")
        glyphs.append((code, advance, width, list(cell.getdata())))

    return ascent, descent, glyphs


def emit(stem, prefix, path, em, name, ascent, descent, glyphs):
    height = ascent + descent
    out = OUT / (stem + ".h")
    guard = stem.upper() + "_H"

    with open(out, "w") as f:
        f.write("/* SPDX-License-Identifier: GPL-3.0-only */\n")
        f.write("/*\n"
                " * GENERATED by tools/make-font.py - do not edit.\n"
                " *\n"
                " * %s, %d-pixel em, antialiased.\n"
                " *\n"
                " * One COVERAGE byte per pixel, 0..255 - not one bit.\n"
                " * The drawing code tints it, so a glyph carries no\n"
                " * colour of its own and one table serves every colour\n"
                " * the shell writes in.\n"
                " *\n"
                " * ascent %d, descent %d, line %d.\n"
                " *\n"
                " * assets/fonts/SOURCE.txt records the file this came\n"
                " * from, its sha256 and its licence.\n"
                " */\n" % (name, em, ascent, descent, height))
        f.write("#ifndef %s\n#define %s\n\n" % (guard, guard))
        f.write("#include <stdint.h>\n\n")
        f.write("#define %s_FIRST %dU\n" % (prefix, FIRST))
        f.write("#define %s_LAST %dU\n" % (prefix, LAST))
        f.write("#define %s_ASCENT %dU\n" % (prefix, ascent))
        f.write("#define %s_DESCENT %dU\n" % (prefix, descent))
        f.write("#define %s_HEIGHT %dU\n" % (prefix, height))
        f.write("#define %s_EM %dU\n" % (prefix, em))
        f.write("/* What to call it, so anything that prints the font's\n"
                " * name prints the one that was rasterised. */\n")
        f.write("#define %s_NAME \"%s\"\n\n" % (prefix, name))

        for code, advance, width, rows in glyphs:
            quote = '"' if chr(code) != '"' else "'"
            f.write("/* %d %s%s%s advance %d */\n"
                    % (code, quote, chr(code), quote, advance))
            f.write("static const uint8_t %s_%d[] = {\n" % (stem, code))
            for row in range(height):
                line = rows[row * width:(row + 1) * width]
                f.write("    " + "".join("%4d," % v for v in line) + "\n")
            f.write("};\n")
        f.write("\n")

        f.write("#ifndef RSD_GLYPH_DEFINED\n#define RSD_GLYPH_DEFINED\n")
        f.write("struct rsd_glyph {\n"
                "    const uint8_t *coverage;\n"
                "    uint32_t width;\n"
                "    uint32_t advance;\n"
                "};\n#endif\n\n")
        f.write("static const struct rsd_glyph %s[] = {\n" % stem)
        for code, advance, width, _ in glyphs:
            f.write("    { %s_%d, %dU, %dU },\n"
                    % (stem, code, width, advance))
        f.write("};\n\n#endif /* %s */\n" % guard)

    return out


def main():
    lines = []
    for stem, prefix, path, em, name in FACES:
        ascent, descent, glyphs = rasterise(path, em)
        out = emit(stem, prefix, path, em, name, ascent, descent, glyphs)
        digest = hashlib.sha256(Path(path).read_bytes()).hexdigest()
        lines.append("    %-22s %-3s %s\n        %s\n        sha256 %s"
                     % (name, "%dpx" % em, path, out.relative_to(ROOT),
                        digest))
        print("wrote %s: %s, %d glyphs, ascent %d line %d, %d KiB"
              % (out.relative_to(ROOT), name, len(glyphs), ascent,
                 ascent + descent, out.stat().st_size // 1024))
    print()
    print("for assets/fonts/SOURCE.txt:")
    print("\n".join(lines))


main()
