#!/usr/bin/env python3
"""The wallpaper, as a table the kernel can hold.

    python3 tools/make-wallpaper-table.py

There is no filesystem under the desktop and no image decoder in it, so
a wallpaper cannot be a file it opens. It has to be a table compiled in.

A 1280x800 image at four bytes a pixel is four megabytes, which is too
much to carry. This gets it to about a third of a megabyte:

  - scaled to the framebuffer's size once, here, with a good filter,
    rather than at every boot with a bad one
  - reduced to 64 colours, WITHOUT dithering. Dithering is the obvious
    thing and it is exactly wrong here: it turns a smooth sky into
    noise, and noise is the one thing run-length encoding cannot
    compress. Undithered banding costs a little in the gradient and
    saves about forty per cent of the file.
  - run-length encoded, since most rows of a night sky are one colour
    for a long way

The decoder is rsd_space_draw() in desktop/src/space.c, which is
eleven lines and holds no state.
"""
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "assets" / "wallpaper" / "rsd-2.5.png"
OUT = ROOT / "desktop" / "src" / "rsd_wallpaper.h"

WIDTH, HEIGHT = 1280, 800
COLOURS = 64

# A run is (count, index). Counts longer than this start a new run, so
# one byte holds the count.
RUN_MAX = 255


def main():
    if not SOURCE.exists():
        raise SystemExit("no wallpaper at %s" % SOURCE)

    image = Image.open(SOURCE).convert("RGB")
    original = image.size
    image = image.resize((WIDTH, HEIGHT), Image.LANCZOS)
    quantised = image.quantize(colors=COLOURS, method=Image.MEDIANCUT,
                               dither=Image.Dither.NONE)

    palette = quantised.getpalette()[:COLOURS * 3]
    try:
        pixels = list(quantised.get_flattened_data())
    except AttributeError:
        pixels = list(quantised.getdata())

    runs = []
    run_index = pixels[0]
    run_length = 1
    for value in pixels[1:]:
        if value == run_index and run_length < RUN_MAX:
            run_length += 1
        else:
            runs.append((run_length, run_index))
            run_index = value
            run_length = 1
    runs.append((run_length, run_index))

    with open(OUT, "w") as out:
        out.write("/* SPDX-License-Identifier: GPL-3.0-only */\n")
        out.write("/*\n"
                  " * GENERATED by tools/make-wallpaper-table.py - do not"
                  " edit.\n"
                  " *\n"
                  " * assets/wallpaper/rsd-2.5.png, %dx%d, scaled to\n"
                  " * %dx%d, reduced to %d colours undithered and run-length\n"
                  " * encoded. See assets/wallpaper/SOURCE.txt for whose it\n"
                  " * is.\n"
                  " *\n"
                  " * %d runs over %d pixels.\n"
                  " */\n"
                  % (original[0], original[1], WIDTH, HEIGHT, COLOURS,
                     len(runs), WIDTH * HEIGHT))
        out.write("#ifndef RSD_WALLPAPER_H\n#define RSD_WALLPAPER_H\n\n")
        out.write("#include <stdint.h>\n\n")
        out.write("#define RSD_WALLPAPER_WIDTH %dU\n" % WIDTH)
        out.write("#define RSD_WALLPAPER_HEIGHT %dU\n" % HEIGHT)
        out.write("#define RSD_WALLPAPER_INKS %dU\n" % COLOURS)
        out.write("#define RSD_WALLPAPER_RUNS %dU\n\n" % len(runs))

        out.write("static const uint32_t rsd_wallpaper_ink"
                  "[RSD_WALLPAPER_INKS] = {\n")
        for i in range(COLOURS):
            r, g, b = palette[i * 3:i * 3 + 3]
            out.write("    0x%02X%02X%02XU,\n" % (r, g, b))
        out.write("};\n\n")

        # Two flat arrays rather than an array of structs: a struct of
        # two bytes pads to four on most targets, which would undo the
        # compression this file exists for.
        out.write("static const uint8_t rsd_wallpaper_run"
                  "[RSD_WALLPAPER_RUNS] = {\n")
        for i in range(0, len(runs), 16):
            out.write("    " + "".join("%3d," % runs[j][0]
                                       for j in range(i, min(i + 16,
                                                             len(runs))))
                      + "\n")
        out.write("};\n\n")
        out.write("static const uint8_t rsd_wallpaper_at"
                  "[RSD_WALLPAPER_RUNS] = {\n")
        for i in range(0, len(runs), 16):
            out.write("    " + "".join("%3d," % runs[j][1]
                                       for j in range(i, min(i + 16,
                                                             len(runs))))
                      + "\n")
        out.write("};\n\n#endif /* RSD_WALLPAPER_H */\n")

    size = OUT.stat().st_size
    print("wrote %s: %d runs, %d colours, %d KiB of source"
          % (OUT.relative_to(ROOT), len(runs), COLOURS, size // 1024))


main()
