#!/usr/bin/env python3
"""The panel's icons, as tables the kernel can hold.

    python3 tools/vendor-icons.py       # first, to fetch them
    python3 tools/make-icons-table.py

Same reason as the wallpaper: there is no filesystem under the desktop
and no PNG decoder in it, so an icon has to be a table compiled in.

These are tiny - six icons at 22x22 is about twelve kilobytes - so there
is no compression here and no palette. Straight 0xAARRGGBB, alpha kept,
because every one of them is drawn over the glass bar and a matte would
show as a grey square round each.

Nothing is redrawn or traced. The pixels are the ones in
assets/icons/, which tools/vendor-icons.py copied byte for byte from
Oxygen and Tango and recorded in assets/icons/SOURCE.txt with the
artists and the licences.
"""
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ICONS = ROOT / "assets" / "icons"
OUT = ROOT / "desktop" / "src" / "rsd_icons.h"

SIZE = 22

# (C name, theme, file). The order is the order of the enum the panel
# indexes with, so it is also the order they appear in the tray.
WANTED = [
    # The panel: task buttons and the tray.
    ("TERMINAL", "oxygen", "utilities-terminal"),
    ("FILES", "oxygen", "system-file-manager"),
    ("SOUND", "oxygen", "audio-volume-high"),
    ("NETWORK", "oxygen", "network-wired"),
    ("POWER", "oxygen", "battery"),
    ("SETTINGS", "oxygen", "preferences-system"),

    # The file manager's toolbar, in the order Nautilus puts them.
    ("BACK", "tango", "go-previous"),
    ("FORWARD", "tango", "go-next"),
    ("UP", "tango", "go-up"),
    ("RELOAD", "tango", "view-refresh"),
    ("HOME", "tango", "go-home"),
    ("FIND", "tango", "edit-find"),

    # Its Places list.
    ("PLACE_HOME", "tango", "user-home"),
    ("PLACE_DESKTOP", "tango", "user-desktop"),
    ("PLACE_DISK", "tango", "drive-harddisk"),
    ("PLACE_NETWORK", "tango", "folder-remote"),
    ("PLACE_DISC", "tango", "media-optical"),
    ("PLACE_TRASH", "tango", "user-trash"),
    ("FOLDER", "tango", "folder"),

    # What is in the view. A file manager that draws every file the
    # same is a file manager you cannot skim.
    ("FILE_TEXT", "tango", "text-x-generic"),
    ("FILE_IMAGE", "tango", "image-x-generic"),
    ("FILE_SOUND", "tango", "audio-x-generic"),
    ("FILE_EXEC", "tango", "application-x-executable"),
    ("FILE_PACKAGE", "tango", "package-x-generic"),
]


def main():
    tables = []
    for name, theme, base in WANTED:
        # The two themes do not ship the same sizes - Oxygen has 22,
        # Tango has 24 and 16 - so take the nearest one at or above the
        # size wanted and come down to it. Scaling down from 24 keeps
        # the drawing; scaling up from 16 would invent detail.
        path = None
        for size in (SIZE, 24, 32, 48, 16):
            candidate = ICONS / theme / ("%dx%d" % (size, size)) / (base + ".png")
            if candidate.exists():
                path = candidate
                break
        if path is None:
            raise SystemExit("missing %s/%s - run tools/vendor-icons.py"
                             % (theme, base))
        image = Image.open(path).convert("RGBA")
        if image.size != (SIZE, SIZE):
            image = image.resize((SIZE, SIZE), Image.LANCZOS)
        tables.append((name, theme, base, list(image.getdata())))

    with open(OUT, "w") as out:
        out.write("/* SPDX-License-Identifier: GPL-3.0-only */\n")
        out.write("/*\n"
                  " * GENERATED by tools/make-icons-table.py - do not edit.\n"
                  " *\n"
                  " * The panel's icons, 0xAARRGGBB, alpha kept because each\n"
                  " * is drawn over the glass bar and a matte would show as a\n"
                  " * grey square round it.\n"
                  " *\n"
                  " * Nothing here is drawn or traced by this project. Every\n"
                  " * pixel came from Oxygen (KDE, LGPL-3+) or Tango\n"
                  " * (freedesktop.org, public domain) by way of\n"
                  " * tools/vendor-icons.py. assets/icons/SOURCE.txt has the\n"
                  " * file each one came from, who drew it, and its sha256.\n"
                  " */\n")
        out.write("#ifndef RSD_ICONS_H\n#define RSD_ICONS_H\n\n")
        out.write("#include <stdint.h>\n\n")
        out.write("#define RSD_ICON_SIZE %dU\n" % SIZE)
        out.write("#define RSD_ICON_COUNT %dU\n\n" % len(tables))

        for i, (name, _, _, _) in enumerate(tables):
            out.write("#define RSD_ICON_%s %dU\n" % (name, i))
        out.write("\n")

        out.write("static const uint32_t rsd_icons[RSD_ICON_COUNT]"
                  "[RSD_ICON_SIZE * RSD_ICON_SIZE] = {\n")
        for name, theme, base, pixels in tables:
            out.write("    {   /* %s: %s/%s */\n" % (name, theme, base))
            for row in range(SIZE):
                cells = pixels[row * SIZE:(row + 1) * SIZE]
                out.write("        " + "".join(
                    "0x%02X%02X%02X%02XU," % (a, r, g, b)
                    for (r, g, b, a) in cells) + "\n")
            out.write("    },\n")
        out.write("};\n\n#endif /* RSD_ICONS_H */\n")

    print("wrote %s: %d icons at %dx%d, %d KiB of source"
          % (OUT.relative_to(ROOT), len(tables), SIZE, SIZE,
             OUT.stat().st_size // 1024))


main()
