#!/usr/bin/env python3
"""Copy the 2010 icon sets into assets/icons/, and record where from.

    sudo apt-get install oxygen-icon-theme tango-icon-theme
    python3 tools/vendor-icons.py

Two themes, because the desktop is copying two different machines.

Oxygen is KDE 4's, drawn 2007 onwards by the Oxygen team, LGPL-3+. It is
what the window decorations, the panel and the terminal on the KDE
reference are wearing, and it is the photorealistic style that says 2010
more than anything else on that screen.

Tango is freedesktop.org's, public domain, and it is what GNOME 2 looked
like. The file manager is copying Nautilus, so its toolbar takes Tango's
arrows and its places list takes Tango's folders.

Nothing here is redrawn and nothing is traced. The files are copied byte
for byte and their sha256 is written down beside them, so any icon on
the screen can be traced back to the file it came from and the person
who drew it. assets/icons/SOURCE.txt is generated by this script and is
not edited by hand.
"""
import hashlib
import os
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "assets" / "icons"

# (theme root, licence, credit, how the theme lays its directories out)
THEMES = {
    "oxygen": {
        "root": Path("/usr/share/icons/oxygen/base"),
        "licence": "LGPL-3+",
        "credit": "The Oxygen team (KDE) - Nuno Pinheiro, David Vignoni, "
                  "David Miller, Johann Ollivier Lapeyre, Kenneth Wimer, "
                  "Riccardo Iaconelli",
        "source": "https://invent.kde.org/frameworks/oxygen-icons5",
        "layout": "{size}x{size}/{group}/{name}.png",
    },
    "tango": {
        "root": Path("/usr/share/icons/Tango"),
        "licence": "public domain",
        "credit": "The Tango Desktop Project - Ulisse Perusin, Steven "
                  "Garrity, Lapo Calamandrei, Ryan Collier, Rodney Dawes, "
                  "Andreas Nilsson, Tuomas Kuosmanen, Garrett LeSage, "
                  "Jakub Steiner",
        "source": "http://tango.freedesktop.org/Tango_Icon_Library",
        "layout": "{size}x{size}/{group}/{name}.png",
    },
}

# What each icon is actually for on our screen, so that a set nobody can
# justify does not quietly grow. If it is not named here it is not
# vendored.
WANTED = [
    # The two native applications, in the terminal's own theme.
    ("oxygen", "apps", "utilities-terminal", (64, 48, 32, 22, 16), "Terminal's icon"),
    ("oxygen", "apps", "system-file-manager", (64, 48, 32, 22, 16), "Files' icon"),

    # The places list down the side of Files, the way Nautilus lists them.
    ("tango", "places", "user-home", (32, 24, 16), "Places: home"),
    ("tango", "places", "folder", (32, 24, 16), "Places: a plain folder"),
    ("tango", "places", "user-desktop", (32, 24, 16), "Places: Desktop"),
    ("tango", "places", "folder-remote", (32, 24, 16), "Places: Network"),
    ("tango", "places", "user-trash", (32, 24, 16), "Places: Trash"),
    ("tango", "devices", "drive-harddisk", (32, 24, 16), "Places: File System"),
    ("tango", "devices", "media-optical", (32, 24, 16), "Places: the disc"),

    # The toolbar across the top of Files.
    ("tango", "actions", "go-previous", (24, 16), "Toolbar: Back"),
    ("tango", "actions", "go-next", (24, 16), "Toolbar: Forward"),
    ("tango", "actions", "go-up", (24, 16), "Toolbar: Up"),
    ("tango", "actions", "view-refresh", (24, 16), "Toolbar: Reload"),
    ("tango", "actions", "go-home", (24, 16), "Toolbar: Home"),
    ("tango", "actions", "edit-find", (24, 16), "Toolbar: Search"),

    # The system tray at the right end of the panel. A 2010 bar has
    # these four and a clock, and nothing else.
    ("oxygen", "status", "audio-volume-high", (22, 16), "Tray: sound"),
    ("oxygen", "devices", "network-wired", (22, 16), "Tray: network"),
    ("oxygen", "devices", "battery", (22, 16), "Tray: power"),
    ("oxygen", "categories", "preferences-system", (22, 16),
     "Tray: settings"),

    # Files in the view. A file manager that draws every file the same
    # is a file manager you cannot skim.
    ("tango", "mimetypes", "text-x-generic", (32, 24, 16), "A text file"),
    ("tango", "mimetypes", "image-x-generic", (32, 24, 16), "An image"),
    ("tango", "mimetypes", "audio-x-generic", (32, 24, 16), "A sound"),
    ("tango", "mimetypes", "application-x-executable", (32, 24, 16), "A program"),
    ("tango", "mimetypes", "package-x-generic", (32, 24, 16), "A package"),
]


def main():
    missing = []
    records = []

    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    for theme, group, name, sizes, why in WANTED:
        spec = THEMES[theme]
        for size in sizes:
            src = spec["root"] / spec["layout"].format(
                size=size, group=group, name=name)
            if not src.exists():
                missing.append(str(src))
                continue
            dst = OUT / theme / ("%dx%d" % (size, size)) / (name + ".png")
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(src, dst)
            digest = hashlib.sha256(dst.read_bytes()).hexdigest()
            records.append((theme, size, name, why, str(src), digest))

    if missing:
        # Say which file, rather than letting a later build complain
        # about an icon that was never copied.
        raise SystemExit("not installed:\n  " + "\n  ".join(missing))

    with open(OUT / "SOURCE.txt", "w") as out:
        out.write("WHERE EVERY ICON CAME FROM\n")
        out.write("==========================\n\n")
        out.write("Generated by tools/vendor-icons.py. Not edited by hand.\n\n")
        out.write("Nothing here was drawn or traced for this project. Every\n")
        out.write("file is a byte-for-byte copy of somebody else's work,\n")
        out.write("and both sets are free to redistribute. The sha256 under\n")
        out.write("each one is the copy in this repository, so any icon on\n")
        out.write("the screen can be traced to the file it came from.\n\n")
        for theme, spec in THEMES.items():
            out.write("-" * 68 + "\n%s\n\n" % theme.upper())
            out.write("  Source   %s\n" % spec["source"])
            out.write("  Licence  %s\n" % spec["licence"])
            out.write("  Drawn by %s\n\n" % spec["credit"])
        out.write("-" * 68 + "\nTHE FILES\n\n")
        for theme, size, name, why, src, digest in records:
            out.write("%s/%dx%d/%s.png\n" % (theme, size, size, name))
            out.write("    for    %s\n" % why)
            out.write("    from   %s\n" % src)
            out.write("    sha256 %s\n\n" % digest)

    print("vendored %d files across %d icons into %s"
          % (len(records), len(WANTED), OUT.relative_to(ROOT)))


main()
